simulations = {'hairpin_s_fwm_poisson_new':
               {'n_structures': (1, 2, 3, 4, 5, 10),
                'common_path': '/scratch/scarste/ensemble_hic/hairpin_s/hairpin_s_fwm_poisson_new_it3_',
                'output_dirs': ('1structures_sn_28replicas',
                              '2structures_sn_30replicas',
                              '3structures_sn_36replicas',
                              '4structures_sn_40replicas',
                              '5structures_sn_45replicas',
                              '10structures_sn_58replicas',               
                              )
                },
               'hairpin_s_fwm_poisson_new_it4_nosphere':
               {'n_structures': (1, 2, 3, 4, 5, 10),
                'common_path': '/scratch/scarste/ensemble_hic/hairpin_s/hairpin_s_fwm_poisson_new_it4_nosphere_',
                'output_dirs': ('1structures_sn_28replicas',
                              '2structures_sn_30replicas',
                              '3structures_sn_36replicas',
                              '4structures_sn_40replicas',
                              '5structures_sn_45replicas',
                              '10structures_sn_58replicas',               
                              )
                },
               '1pga_1shf_fwm_poisson_new_it3':
               {'n_structures': (1, 2, 3, 4, 5, 10),
                'common_path': '/scratch/scarste/ensemble_hic/proteins/1pga_1shf_fwm_poisson_new_it3_',
                'output_dirs': ('1structures_sn_58replicas',
                              '2structures_sn_54replicas',
                              '3structures_sn_66replicas',
                              '4structures_sn_70replicas',
                              '5structures_sn_74replicas',
                              '10structures_sn_98replicas',               
                              )
                },
               'K562_new_smallercd':
               {'n_structures': {1, 2, 3, 4, 5, 7, 10, 20, 50},
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/K562_new_smallercd_',
                'output_dirs': ('it3_1structures_sn_158replicas',
                              'it2_2structures_sn_109replicas',
                              'it2_3structures_sn_93replicas',
                              'it2_4structures_sn_90replicas',
                              'it2_5structures_sn_91replicas',
                              'it2_7structures_sn_94replicas',
                              'it2_10structures_sn_98replicas',
                              '20structures_sn_98replicas',
                              '50structures_sn_112replicas',               
                              )
                },
               'K562_new_smallercd_nosphere':
               {'n_structures': (1, 2, 3, 4, 7, 10, 15, 20, 30, 40, 50),
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/K562_new_smallercd_nosphere_',
                'output_dirs': ('1structures_sn_136replicas',
                               '2structures_sn_108replicas',
                               '3structures_sn_91replicas',
                              '4structures_sn_90replicas',
                              '7structures_sn_94replicas',
                              '10structures_sn_98replicas',
                              '15structures_sn_112replicas',
                              '20structures_sn_112replicas',
                              '30structures_sn_109replicas',
                              '40structures_sn_109replicas',
                              'it2_50structures_sn_109replicas',
                              )
                },
               'K562_new_smallercd_nosphere_alpha50':
               {'n_structures': (1, 2, 3, 4, 5, 7, 10, 15, 20, 30, 40, 50),
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/K562_new_smallercd_nosphere_alpha50_',
                'output_dirs': ('1structures_sn_136replicas',
                               '2structures_sn_108replicas',
                               '3structures_sn_91replicas',
                              '4structures_sn_90replicas',
                              '5structures_sn_90replicas',
                              '7structures_sn_94replicas',
                              '10structures_sn_98replicas',
                              '15structures_sn_112replicas',
                              '20structures_sn_112replicas',
                              '30structures_sn_109replicas',
                              '40structures_sn_109replicas',
                              '50structures_sn_109replicas',
                              )
                },
               'GM12878_new_smallercd':
               {'n_structures': (1, 2, 3, 4, 7, 20),
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/GM12878_new_smallercd_',
                'output_dirs': ('1structures_sn_136replicas',
                              '2structures_sn_108replicas',
                              '3structures_sn_91replicas',
                              '4structures_sn_90replicas',
                              '7structures_sn_94replicas',
                              '20structures_sn_112replicas',
                              )
                },
               'GM12878_new_smallercd_nosphere':
               {'n_structures': (1, 2, 3, 4, 7, 10, 15, 20, 30, 40, 50),
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/GM12878_new_smallercd_nosphere_',
                'output_dirs': ('it2_1structures_sn_139replicas',
                              'it2_2structures_sn_120replicas',
                              'it2_3structures_sn_108replicas',
                              'it2_4structures_sn_103replicas',
                              'it2_7structures_sn_111replicas',
                              'it2_10structures_sn_113replicas',
                              '15structures_sn_122replicas',
                              '20structures_sn_122replicas',
                              '30structures_sn_122replicas',
                              '40structures_sn_122replicas',
                              'it2_50structures_sn_122replicas',
                              )
                },
               'GM12878_new_smallercd_nosphere_fixed':
               {'n_structures': (1, 2, 3, 4, 7, 10, 15, 20, 30, 40, 50),
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/GM12878_new_smallercd_nosphere_fixed_',
                'output_dirs': ('1structures_sn_137replicas',
                              '2structures_sn_119replicas',
                              '3structures_sn_106replicas',
                              '4structures_sn_100replicas',
                              '7structures_sn_111replicas',
                              '10structures_sn_113replicas',
                              '15structures_sn_118replicas',
                              '20structures_sn_122replicas',
                              '30structures_sn_131replicas',
                              '40structures_sn_140replicas',
                              '50structures_sn_149replicas',
                              )
                },
               'K562_new_smallercd_nosphere_fixed':
               {'n_structures': (1, 2, 3, 4, 7, 10, 15, 20, 30, 40, 50),
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/K562_new_smallercd_nosphere_it2_fixed_',
                'output_dirs': ('1structures_sn_135replicas',
                              '2structures_sn_114replicas',
                              '3structures_sn_91replicas',
                              '4structures_sn_90replicas',
                              #'5structures_sn_91replicas',
                              '7structures_sn_93replicas',
                              '10structures_sn_97replicas',
                              '15structures_sn_104replicas',
                              '20structures_sn_109replicas',
                              '30structures_sn_120replicas',
                              '40structures_sn_130replicas',
                              '50structures_sn_139replicas',
                              )
                },
               'GM12878_new_smallercd_nosphere_alpha50':
               {'n_structures': (1, 2, 3, 7, 10, 15, 20, 30, 40, 50),
                'common_path': '/scratch/scarste/ensemble_hic/bau2011/GM12878_new_smallercd_nosphere_alpha50_',
                'output_dirs': ('1structures_sn_139replicas',
                              '2structures_sn_120replicas',
                              '3structures_sn_108replicas',
                               #'4structures_sn_103replicas',
                              '7structures_sn_111replicas',
                              '10structures_sn_113replicas',
                              '15structures_sn_122replicas',
                              '20structures_sn_122replicas',
                              '30structures_sn_122replicas',
                              '40structures_sn_122replicas',
                              '50structures_sn_122replicas',
                              )
                },

               # 'rao2014_randominit':
               # {'n_structures': (5, 10, 20, 30, 40, 50),
               #  'common_path': '/scratch/scarste/ensemble_hic/rao2014/chr16_randominit_',
               #  'output_dirs': ('it3_5structures_sn_146replicas',
               #                  'it3_10structures_sn_172replicas',
               #                  'it2_20structures_sn_189replicas',
               #                  'it1_30structures_sn_210replicas',
               #                  'it1_40structures_sn_210replicas',
               #                  'it1_50structures_sn_195replicas',
               #                )
               #  }
               'rao2014_randominit':
               {'n_structures': (5, 10, 20, 30, 40, 50),
                'common_path': '/scratch/scarste/ensemble_hic/rao2014/chr1_randominit_',
                'output_dirs': ('it3_5structures_sn_285replicas',
                                'it3_10structures_sn_338replicas',
                                'it1_20structures_sn_210replicas',
                                'it3_30structures_sn_481replicas',
                                'it3_40structures_sn_481replicas',
                                'it3_50structures_sn_481replicas',
                              )
                },
               'eser2017_chr4':
               {'n_structures': (1, 10, 20, 30, 50),
                'common_path': '/scratch/scarste/ensemble_hic/eser2017/chr4_nozeros_',
                'output_dirs': ('1structures_sn_147replicas',
                                'it2_10structures_sn_153replicas',
                                'it2_20structures_sn_153replicas',
                                '30structures_sn_158replicas',
                                'it2_50structures_sn_153replicas',
                              )
                },
               'eser2017_whole_genome':
               {'n_structures': (10, 20, 50, 100),
                'common_path': '/scratch/scarste/ensemble_hic/eser2017/whole_genome_rDNA23_arbona2017_',
                'output_dirs': ('it2_10structures_sn_438replicas',
                                'it2_20structures_sn_366replicas',
                                'it5_50structures_sn_629replicas',
                                'it3_100structures_sn_725replicas',
                              )
                },
               'nora2012':
               {'n_structures': (1, 5, 10, 20, 20, 20, 20, 20, 30, 30, 30, 40, 40, 40,
                                 #100
                                 ),
                'common_path': '/scratch/scarste/ensemble_hic/nora2012/bothdomains_',
                'output_dirs': ('it3_1structures_298replicas',
                                'it3_5structures_218replicas',
                                '10structures_297replicas',
                                'it3_20structures_309replicas',
                                'it3_rep3_20structures_309replicas',
                                'it3_rep4_20structures_309replicas',
                                'fixed_it3_20structures_309replicas',
				'fixed_it3_rep2_20structures_309replicas',
                                'rep1_30structures_330replicas',
                                'rep2_30structures_330replicas',
                                'rep3_30structures_330replicas',
                                'it2_40structures_330replicas',
                                'it2_rep1_40structures_330replicas',
                                'it2_rep2_40structures_330replicas',
                                #'rep3_100structures_330replicas',
                              )
                },
               'nora2012_female':
               {'n_structures': (1, 5, 10, 20, 20, 20, 30, 30, 30, 40, 40, 40),
                'common_path': '/scratch/scarste/ensemble_hic/nora2012/female_bothdomains_',
                'output_dirs': ('1structures_217replicas',
                                '5structures_217replicas',
                                '10structures_217replicas',
                                '20structures_217replicas',
                                'rep2_20structures_217replicas',
                                'rep3_20structures_217replicas',
                                'rep1_30structures_252replicas',
                                'rep2_30structures_252replicas',
                                'rep3_30structures_252replicas',
                                '40structures_252replicas',
                                'rep2_40structures_252replicas',
                                'rep3_40structures_252replicas',
                                )
                },
               'nora2012_female_day2':
               {'n_structures': (1, 5, 10, 20, 20, 20, 30, 30, 30, 40, 40, 40),
                'common_path': '/scratch/scarste/ensemble_hic/nora2012/female_day2_bothdomains_',
                'output_dirs': ('1structures_217replicas',
                                '5structures_217replicas',
                                '10structures_217replicas',
                                '20structures_217replicas',
                                'rep2_20structures_217replicas',
                                'rep3_20structures_217replicas',
                                'rep1_30structures_252replicas',
                                'rep2_30structures_252replicas',
                                'rep3_30structures_252replicas',
                                '40structures_252replicas',
                                'rep2_40structures_252replicas',
                                'rep3_40structures_252replicas',
                              )
                },
               'nora2012_noii3':
               {'n_structures': (20, 40),
                'common_path': '/scratch/scarste/ensemble_hic/nora2012/bothdomains_noii3_',
                'output_dirs': ('20structures_330replicas',
                                '40structures_330replicas',
                              )
                },
               'nora2012_15kbbins':
               {'n_structures': (1, 5, 10, 20, 40, 100),
                'common_path': '/scratch/scarste/ensemble_hic/nora2012/15kbbins_bothdomains_',
                'output_dirs': ('1structures_159replicas',
                                'it4_5structures_159replicas',
                                'it4_10structures_150replicas',
                                'it4_20structures_148replicas',
                                #'30structures_172replicas',
                                #'it2_40structures_111replicas',
                                'it4_40structures_172replicas',
                                'it3_100structures_186replicas',
                              )
                },
               'nora2012_15kbbins_fixed':
               {'n_structures': (1, 5, 10, 20, 40, 100),
                'common_path': '/scratch/scarste/ensemble_hic/nora2012/15kbbins_bothdomains_fixed_',
                'output_dirs': ('it4_1structures_82replicas',
                                'it4_5structures_159replicas',
                                'it4_10structures_150replicas',
                                'it4_20structures_148replicas',
                                '30structures_172replicas',
                                'it4_40structures_172replicas',
                                'it3_100structures_186replicas',
                              )
                },

               }
